# This is a basic workflow to help you get started with Actions

name: tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Install Python 3
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get update -yy
          sudo apt-get install ghostscript -yy

      - name: Run tests with pytest
        run: pytest -v -rsx --mpl-generate-summary=html --mpl-results-path=/tmp/pytest-mpl-results --color=yes

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: "plot results"
          path: /tmp/pytest-mpl-results
